
name : Jekyll

on:
    workflow_dispatch:

    push:
        branches : [ 'Latest' ]


permissions:
    id-token : write
    contents : read
    pages : write


concurrency:
    cancel-in-progress : false
    group : 'Jekyll'

jobs:

    Build:

        runs-on : ubuntu-latest

        steps:
            -   name : Checkout
                uses : actions/checkout@v6

            -   name : Setup Pages
                uses : actions/configure-pages@v5

            -   name : Build Jekyll
                uses : actions/jekyll-build-pages@v1

                with:
                    destination : ./Page
                    source : ./Source

            -   name : Upload artifact
                uses : actions/upload-pages-artifact@v4

    Deploy:

        runs-on : ubuntu-latest
        needs : Build

        environment:
            name : github-pages
            url : ${{ steps.Deployment.outputs.page_url }}

        steps:

            -   name : Deploy
                uses : actions/deploy-pages@v4
                id : Deployment
